services:
  ipfs_cluster_peer1:
    build: .
    container_name: ipfs_cluster_peer1
    environment:
      CLUSTER_SECRET: "338d9fd88a87c551a91c13314da0822f4da6e94e08de45c706f1b787902b9104"
      CLUSTER_IPFS_CONNECT: "/ip4/127.0.0.1/tcp/5001"
      IPFS_API_ADDRESS: "/ip4/0.0.0.0/tcp/5001"
      CLUSTER_RESTAPI_HTTP_LISTEN_MULTIADDRESS: "/ip4/0.0.0.0/tcp/9094"
    ports:
      - "4001:4001"
      - "5001:5001"
      - "8080:8080"
      - "9094:9094"
      - "9095:9095"
    volumes:
      - ./cluster_data_peer1:/data/ipfs-cluster

  ipfs_cluster_peer2:
    build: .
    container_name: ipfs_cluster_peer2
    environment:
      CLUSTER_SECRET: "338d9fd88a87c551a91c13314da0822f4da6e94e08de45c706f1b787902b9104"
      CLUSTER_IPFS_CONNECT: "/ip4/127.0.0.1/tcp/5001"
      CLUSTER_PEER_ADDRESSES: "/ip4/ipfs_cluster_peer1/tcp/9096/p2p/12D3KooWNNtS2A4XZUERMS4u6KL6xiNaAgqDhbrNNWo2mo8aKRdR"
      IPFS_API_ADDRESS: "/ip4/0.0.0.0/tcp/5001"
      CLUSTER_RESTAPI_HTTP_LISTEN_MULTIADDRESS: "/ip4/0.0.0.0/tcp/9094"
    ports:
      - "4002:4001"
      - "5002:5001"
      - "8082:8080"
      - "9096:9094"
      - "9097:9095"
    volumes:
      - ./cluster_data_peer2:/data/ipfs-cluster

  ipfs_cluster_peer3:
    build: .
    container_name: ipfs_cluster_peer3
    environment:
      CLUSTER_SECRET: "338d9fd88a87c551a91c13314da0822f4da6e94e08de45c706f1b787902b9104"
      CLUSTER_IPFS_CONNECT: "/ip4/127.0.0.1/tcp/5001"
      CLUSTER_PEER_ADDRESSES: "/ip4/ipfs_cluster_peer1/tcp/9096/p2p/12D3KooWNNtS2A4XZUERMS4u6KL6xiNaAgqDhbrNNWo2mo8aKRdR"
      IPFS_API_ADDRESS: "/ip4/0.0.0.0/tcp/5001"
      CLUSTER_RESTAPI_HTTP_LISTEN_MULTIADDRESS: "/ip4/0.0.0.0/tcp/9094"
    ports:
      - "4003:4001"
      - "5003:5001"
      - "8083:8080"
      - "9098:9094"
      - "9099:9095"
    volumes:
      - ./cluster_data_peer3:/data/ipfs-cluster

  pinning_service:
    build:
      context: .
      dockerfile: Dockerfile.node
    container_name: pinning_service
    ports:
      - "3000:3000"
    depends_on:
      - ipfs_cluster_peer1
